site:
  title: Master CSMI
  url: https://master-csmi.github.io/csmi
  start_page: csmi::index.adoc
content:
  sources:
  - url: https://github.com/master-csmi/csmi
    branches: main
  - url: https://github.com/master-csmi/csmi-stages-2020
    branches: main    
  - url: https://github.com/master-csmi/csmi-stages-2021
    branches: main
  - url: https://github.com/master-csmi/csmi-stages-2022
    branches: main    
ui:
  bundle:
    url: https://gitlab.com/feelpp/antora-ui-default/-/jobs/artifacts/feelpp2/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  clean: true
  dir: public
  
asciidoc:
  attributes:
    responsable: Christophe Prud'homme <prudhomme@unistra.fr>
    project_version: 0.1
    deploymentRoot: ""
    numbered: true
    allow-uri-read: true
    hide-uri-scheme: true
    feelpp: Feel++
    angiotk: AngioTK
    4fastsim: 4FastSim
    stem: latexmath
    hemotumpp: Hemotum++
    eye2brain: Eye2Brain
    swimmer: Swimmer
    csmi: CSMI
    cemosis: https://www.cemosis.fr[Cemosis]
    amies: https://www.agence-maths-entreprises.fr/[AMIES]
  extensions:
    - "@djencks/asciidoctor-template"